[package]
name = "water-level"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bitflags = "2.8.0"
dotenv = "0.15.0"
reqwest = "0.12.12"
rppal = "0.22.1"
tokio = { version = "1.43.0", features = ["full"] }
